# Generated by Django 4.2 on 2024-05-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0003_alter_inmueble_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='comuna',
            field=models.CharField(choices=[('alhue', 'Alhué'), ('buin', 'Buin'), ('calera_de_tango', 'Calera de Tango'), ('cerrillos', 'Cerrillos'), ('cerro_navia', 'Cerro Navia'), ('colina', 'Colina'), ('conchali', 'Conchalí'), ('curacavi', 'Curacaví'), ('el_bosque', 'El Bosque'), ('el_monte', 'El Monte'), ('estacion_central', 'Estación Central'), ('huechuraba', 'Huechuraba'), ('independencia', 'Independencia'), ('isla_de_maipo', 'Isla de Maipo'), ('la_cisterna', 'La Cisterna'), ('la_florida', 'La Florida'), ('la_granja', 'La Granja'), ('la_pintana', 'La Pintana'), ('la_reina', 'La Reina'), ('lampa', 'Lampa'), ('las_condes', 'Las Condes'), ('lo_barnechea', 'Lo Barnechea'), ('lo_espejo', 'Lo Espejo'), ('lo_prado', 'Lo Prado'), ('macul', 'Macul'), ('maipu', 'Maipú'), ('melipilla', 'Melipilla'), ('nunoa', 'Ñuñoa'), ('padre_hurtado', 'Padre Hurtado'), ('penaflor', 'Peñaflor'), ('penalolen', 'Peñalolén'), ('pirque', 'Pirque'), ('puente_alto', 'Puente Alto'), ('providencia', 'Providencia'), ('pudahuel', 'Pudahuel'), ('quilicura', 'Quilicura'), ('quinta_normal', 'Quinta Normal'), ('recoleta', 'Recoleta'), ('renca', 'Renca'), ('san_bernardo', 'San Bernardo'), ('san_joaquin', 'San Joaquín'), ('san_jose_de_maipo', 'San José de Maipo'), ('san_miguel', 'San Miguel'), ('san_pedro', 'San Pedro'), ('san_ramon', 'San Ramón'), ('santiago', 'Santiago'), ('talagante', 'Talagante'), ('til_til', 'Til Til'), ('vitacura', 'Vitacura')], max_length=50),
        ),
    ]
