# Generated by Django 4.2 on 2024-05-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0004_alter_inmueble_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='propietario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='arriendos.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(upload_to='img/inmuebles/'),
        ),
    ]
