# Generated by Django 4.2 on 2024-05-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0007_alter_inmueble_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(max_length=300),
        ),
    ]
