# Generated by Django 4.2 on 2024-05-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0010_solicitudarriendo_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarriendo',
            name='aceptada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudarriendo',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
