# Generated by Django 4.2 on 2024-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0011_solicitudarriendo_aceptada_solicitudarriendo_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='aceptada',
            field=models.BooleanField(default=None),
        ),
    ]
