# Generated by Django 4.2 on 2024-05-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0012_alter_solicitudarriendo_aceptada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='aceptada',
            field=models.BooleanField(default=False),
        ),
    ]
