# Generated by Django 4.2 on 2024-05-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0013_alter_solicitudarriendo_aceptada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudarriendo',
            name='aceptada',
        ),
        migrations.AddField(
            model_name='solicitudarriendo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
            preserve_default=False,
        ),
    ]
